Feature/schema fix
wirenboard/wb-knxd-config pull request #1
Opened 2020-05-18 14:21 UTC by munrexio

Много разных правок. Основное: добавлены проверки значений в схеме, короткие названия параметров заменил на длинные, удалил лишние файлы, подправил значения конфига по умолчанию.

2020-05-19 18:32 UTC, evgeny-boger requested changes

2020-05-19 18:32 UTC, evgeny-boger commented on debian/postrm
>  if [ "$1" = "purge" ] ; then
а это точно надо? Вроде же debian сам при purge всё удалит

2020-05-19 18:32 UTC, evgeny-boger commented on debian/postinst
> +addgroup knxd dialout
надо проверить, как работает это всё, если в системе нет knxd, нет юзера, и knxd ставится вместе с wb-knxd-config по его зависимостям.

2020-05-19 18:32 UTC, evgeny-boger commented on wb-knxd-config.sh
> +echo "KNXD_OPTS=\"$trace$error -e $eibAddr -E $clientAddrs $groupCache$forced$discovery$tunnelling$routing$server$listenTcp$listenLocal -b $layer2 $otherOptions\"" > /etc/knxd.conf
первой строчкой в /etc/knxd.conf надо положить предупреждение про то, что он автоматически генерируется из /etc/wb-knxd-config.conf пакетом wb-knxd-config и редактировать его вручную бесполезно.

2020-05-27 22:43 UTC, evgeny-boger commented
>надо проверить, как работает это всё, если в системе нет knxd, нет юзера, и knxd ставится вместе с wb-knxd-config по его зависимостям.

а это проверил?

2020-05-28 13:39 UTC, munrexio commented
> > надо проверить, как работает это всё, если в системе нет knxd, нет юзера, и knxd ставится вместе с wb-knxd-config по его зависимостям.
> 
> а это проверил?
Да, проверял работает.
![knxd2](https://user-images.githubusercontent.com/51443304/83148494-b4e27280-a101-11ea-8123-698594993f14.PNG)

2020-05-28 13:52 UTC, merged